const C=window.SUPABASE_CONFIG||{};
const configured=C.url&&C.anonKey&&!C.url.includes('YOUR_PROJECT')&&!C.anonKey.includes('YOUR_');
const SKEY='thpt_v3_local';
let session=JSON.parse(localStorage.getItem('thpt_session')||'null');
let db=JSON.parse(localStorage.getItem(SKEY)||'null')||{students:[],classes:[],grades:[],attendance:[],awards:[],violations:[],years:[{id:'local-year',name:'2026-2027',is_current:true}]};
let page='dashboard',currentYear=localStorage.getItem('thpt_year')||'2026-2027';
const app=document.querySelector('#app');
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const save=()=>localStorage.setItem(SKEY,JSON.stringify(db));
const student=id=>db.students.find(s=>s.id===id);
const classBy=id=>db.classes.find(c=>c.id===id);
function calc(g){let r=(g.regular||[]).map(Number).filter(Number.isFinite);let w=r.length+5;return w?((r.reduce((a,b)=>a+b,0)+(+g.mid||0)*2+(+g.final||0)*3)/w):0}
function rate(id){let a=db.attendance.filter(x=>x.student_id===id);return a.length?Math.round(a.filter(x=>x.status==='present').length/a.length*100):100}
function gradeAvg(id){let a=db.grades.filter(x=>x.student_id===id);return a.length?+(a.reduce((s,g)=>s+calc(g),0)/a.length).toFixed(2):0}
function st(s){let a=gradeAvg(s.id),r=rate(s.id);return a<5||r<85?'Cần hỗ trợ':a<6.5||r<90?'Cần chú ý':a<8?'Khá':'Tốt'}
async function api(path,opts={}){if(!configured||!session?.access_token)throw Error('Chưa cấu hình Supabase hoặc chưa đăng nhập');let r=await fetch(C.url+'/rest/v1/'+path,{...opts,headers:{apikey:C.anonKey,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json',Prefer:'return=representation',...(opts.headers||{})}});if(!r.ok)throw Error(await r.text());return r.status===204?[]:r.json()}
async function auth(path,body){let r=await fetch(C.url+'/auth/v1/'+path,{method:'POST',headers:{apikey:C.anonKey,'Content-Type':'application/json'},body:JSON.stringify(body)});let d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||'Đăng nhập thất bại');return d}
async function login(e){e.preventDefault();let f=new FormData(e.target);try{let d=await auth('token?grant_type=password',{email:f.get('email'),password:f.get('password')});session=d;localStorage.setItem('thpt_session',JSON.stringify(d));await syncDown();render()}catch(x){alert(x.message)}}
async function signup(e){e.preventDefault();let f=new FormData(e.target);try{await auth('signup',{email:f.get('email'),password:f.get('password'),data:{full_name:f.get('name')}});alert('Đã tạo tài khoản. Hãy kiểm tra email nếu Supabase yêu cầu xác nhận, sau đó đăng nhập.');renderLogin()}catch(x){alert(x.message)}}
function logout(){session=null;localStorage.removeItem('thpt_session');renderLogin()}
async function syncDown(){if(!configured||!session)return;try{let [years,classes,students,grades,attendance,awards,violations]=await Promise.all(['academic_years?select=*&order=name.desc','classes?select=*&order=name','students?select=*&order=full_name','grades?select=*','attendance?select=*','awards?select=*&order=award_date.desc','violations?select=*&order=violation_date.desc'].map(x=>api(x)));db={years,classes,students,grades,attendance,awards,violations};if(years.find(x=>x.is_current))currentYear=years.find(x=>x.is_current).name;save()}catch(x){console.warn(x)}}
async function push(table,row,method='POST',id=''){try{await api(table+(id?'?id=eq.'+encodeURIComponent(id):''),{method,body:JSON.stringify(row)})}catch(x){alert('Lưu máy chủ thất bại: '+x.message)}}
function loginScreen(){app.innerHTML=`<div class="login"><div class="loginbox"><div class="logo">🎓</div><h1>Quản lý học sinh THPT</h1><p>Đăng nhập hệ thống giáo viên</p><form onsubmit="login(event)"><input name="email" type="email" required placeholder="Email giáo viên"><input name="password" type="password" required placeholder="Mật khẩu"><button class="btn">Đăng nhập</button></form>${configured?'':'<div class="setup">⚙️ Supabase chưa được cấu hình. Hệ thống vẫn có thể chạy dữ liệu cục bộ; hãy điền <b>config.js</b> để bật đăng nhập trực tuyến.</div>'}<button class="linkbtn" onclick="renderSignup()">Tạo tài khoản giáo viên</button></div></div>`}
function renderLogin(){loginScreen()}
function renderSignup(){app.innerHTML=`<div class="login"><div class="loginbox"><div class="logo">👨‍🏫</div><h1>Tạo tài khoản</h1><form onsubmit="signup(event)"><input name="name" required placeholder="Họ và tên"><input name="email" type="email" required placeholder="Email"><input name="password" type="password" minlength="6" required placeholder="Mật khẩu tối thiểu 6 ký tự"><button class="btn">Đăng ký</button></form><button class="linkbtn" onclick="renderLogin()">← Quay lại đăng nhập</button></div></div>`}
function shell(content){let yrs=(db.years||[]).map(y=>`<option ${y.name===currentYear?'selected':''}>${esc(y.name)}</option>`).join('');app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand">🎓 QUẢN LÝ HỌC SINH<span>THPT • ${esc(currentYear)}</span></div><nav class="nav">${[['dashboard','🏠 Tổng quan'],['students','👨‍🎓 Học sinh'],['classes','🏫 Lớp học'],['grades','📊 Điểm số'],['attendance','📅 Điểm danh'],['awards','🏆 Khen thưởng'],['violations','⚠️ Vi phạm'],['reports','📄 Báo cáo'],['settings','⚙️ Cài đặt']].map(x=>`<button class="${page===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}</nav><button class="logout" onclick="logout()">↪ Đăng xuất</button></aside><main class="main"><div class="yearbar">Năm học <select onchange="changeYear(this.value)">${yrs||'<option>2026-2027</option>'}</select><span>${session?.user?.email||'Chế độ cục bộ'}</span></div>${content}</main></div>`}
function header(t,s,a=''){return `<div class="top"><div><h1>${t}</h1><p>${s}</p></div>${a}</div>`}
function dashboard(){let total=db.students.length,good=db.students.filter(s=>gradeAvg(s.id)>=8).length,need=db.students.filter(s=>st(s)!=='Tốt').length; shell(header('Tổng quan','Theo dõi tình hình học tập, chuyên cần và rèn luyện')+`<section class="cards"><div class="card"><div class="label">👨‍🎓 Học sinh</div><div class="value">${total}</div></div><div class="card"><div class="label">🏫 Lớp học</div><div class="value">${db.classes.length}</div></div><div class="card"><div class="label">⭐ ĐTB ≥ 8</div><div class="value">${good}</div></div><div class="card"><div class="label">🔔 Cần quan tâm</div><div class="value">${need}</div></div></section><section class="grid"><div class="card"><h2>Trạng thái học sinh</h2>${['Tốt','Khá','Cần chú ý','Cần hỗ trợ'].map(x=>`<div>${x} <b>${db.students.filter(s=>st(s)===x).length}</b></div>`).join('')}</div><div class="card"><h2>Cảnh báo</h2><div class="alert">⚠️ ${db.students.filter(s=>rate(s.id)<85).length} học sinh chuyên cần dưới 85%</div><div class="alert">📉 ${db.students.filter(s=>gradeAvg(s.id)>0&&gradeAvg(s.id)<5).length} học sinh có ĐTB dưới 5</div><div class="alert">🏆 ${db.awards.length} lượt khen thưởng</div><div class="alert">⚠️ ${db.violations.length} lượt vi phạm</div></div></section>`)}
function studentsPage(){shell(header('Học sinh','Quản lý hồ sơ học sinh',`<button class="btn" onclick="studentForm()">＋ Thêm học sinh</button>`)+`<div class="toolbar"><input id="q" placeholder="🔍 Tìm mã hoặc họ tên" oninput="filterStudents()"><select id="cf" onchange="filterStudents()"><option value="">Tất cả lớp</option>${db.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><button class="btn secondary" onclick="exportCSV('students')">⬇ CSV</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Họ tên</th><th>Lớp</th><th>Giới tính</th><th>ĐTB</th><th>Chuyên cần</th><th>Trạng thái</th><th></th></tr></thead><tbody id="srows">${studentRows(db.students)}</tbody></table></div>`)}
function studentRows(list){return list.map(s=>`<tr><td>${esc(s.code||s.id)}</td><td><b>${esc(s.full_name||s.name)}</b></td><td>${esc(classBy(s.class_id)?.name||s.class||'')}</td><td>${esc(s.gender||'')}</td><td>${gradeAvg(s.id).toFixed(2)}</td><td>${rate(s.id)}%</td><td><span class="badge ${st(s)==='Tốt'?'ok':st(s)==='Khá'?'info':st(s)==='Cần chú ý'?'warn':'danger'}">${st(s)}</span></td><td><button class="linkbtn" onclick="studentForm('${s.id}')">Sửa</button><button class="linkbtn dangerText" onclick="removeStudent('${s.id}')">Xóa</button></td></tr>`).join('')}
function filterStudents(){let q=(document.querySelector('#q')?.value||'').toLowerCase(),c=document.querySelector('#cf')?.value||'';document.querySelector('#srows').innerHTML=studentRows(db.students.filter(s=>(s.full_name||s.name||'').toLowerCase().includes(q)||(s.code||s.id).toLowerCase().includes(q)) .filter(s=>!c||s.class_id===c))}
function studentForm(id=''){let s=student(id)||{};modal(`<h2>${id?'Sửa':'Thêm'} học sinh</h2><form onsubmit="saveStudent(event,'${id}')"><div class="formgrid"><label>Mã HS<input name="code" required value="${esc(s.code||'')}" ${id?'readonly':''}></label><label>Họ tên<input name="name" required value="${esc(s.full_name||s.name||'')}"></label><label>Lớp<select name="class_id">${db.classes.map(c=>`<option value="${c.id}" ${c.id===s.class_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Giới tính<select name="gender"><option ${s.gender==='Nam'?'selected':''}>Nam</option><option ${s.gender==='Nữ'?'selected':''}>Nữ</option></select></label><label>Điện thoại<input name="phone" value="${esc(s.phone||'')}"></label><label>Ngày sinh<input name="dob" type="date" value="${esc(s.date_of_birth||'')}"></label><label>Phụ huynh<input name="parent" value="${esc(s.parent_name||'')}"></label><label>ĐT phụ huynh<input name="parent_phone" value="${esc(s.parent_phone||'')}"></label></div><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
async function saveStudent(e,id){e.preventDefault();let f=new FormData(e.target),row={code:f.get('code'),full_name:f.get('name'),class_id:f.get('class_id')||null,gender:f.get('gender'),phone:f.get('phone'),date_of_birth:f.get('dob')||null,parent_name:f.get('parent'),parent_phone:f.get('parent_phone')};if(id){Object.assign(student(id),row);if(configured&&session)await push('students?id=eq.'+encodeURIComponent(id),row,'PATCH')}else{row.id=uid('hs');db.students.push(row);if(configured&&session){try{let r=await api('students',{method:'POST',body:JSON.stringify(row)});if(r[0])Object.assign(row,r[0])}catch(x){alert(x.message)}}}save();closeModal();studentsPage()}
async function removeStudent(id){if(!confirm('Xóa học sinh và dữ liệu liên quan?'))return;db.students=db.students.filter(x=>x.id!==id);['grades','attendance','awards','violations'].forEach(k=>db[k]=db[k].filter(x=>(x.student_id||x.studentId)!==id));if(configured&&session)await push('students?id=eq.'+encodeURIComponent(id),{},'DELETE');save();studentsPage()}
function classesPage(){shell(header('Lớp học','Danh sách lớp theo năm học',`<button class="btn" onclick="classForm()">＋ Thêm lớp</button>`)+`<div class="table-wrap"><table class="table"><thead><tr><th>Lớp</th><th>Sĩ số</th><th>Nam</th><th>Nữ</th><th>ĐTB</th><th>Chuyên cần</th></tr></thead><tbody>${db.classes.map(c=>{let ss=db.students.filter(s=>s.class_id===c.id),a=ss.length?ss.reduce((z,s)=>z+gradeAvg(s.id),0)/ss.length:0,r=ss.length?ss.reduce((z,s)=>z+rate(s.id),0)/ss.length:100;return `<tr><td><b>${esc(c.name)}</b></td><td>${ss.length}</td><td>${ss.filter(s=>s.gender==='Nam').length}</td><td>${ss.filter(s=>s.gender==='Nữ').length}</td><td>${a.toFixed(2)}</td><td>${Math.round(r)}%</td></tr>`}).join('')}</tbody></table></div>`)}
function classForm(){modal(`<h2>Thêm lớp</h2><form onsubmit="saveClass(event)"><label>Tên lớp<input name="name" required placeholder="Ví dụ: 10A1"></label><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
async function saveClass(e){e.preventDefault();let name=new FormData(e.target).get('name').trim();if(db.classes.some(c=>c.name===name)){alert('Lớp đã tồn tại');return}let row={id:uid('cl'),name,academic_year_id:db.years.find(y=>y.name===currentYear)?.id||null};db.classes.push(row);if(configured&&session)await push('classes',row);save();closeModal();classesPage()}
function gradesPage(){shell(header('Điểm số','Quản lý điểm theo môn và học kỳ',`<button class="btn" onclick="gradeForm()">＋ Nhập điểm</button>`)+`<div class="toolbar"><select id="gc" onchange="renderGrades()"><option value="">Tất cả lớp</option>${db.classes.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select><select id="gs" onchange="renderGrades()"><option value="">Tất cả môn</option>${['Toán','Ngữ văn','Tin học','Vật lý','Hóa học','Tiếng Anh'].map(x=>`<option>${x}</option>`).join('')}</select><select id="gm" onchange="renderGrades()"><option value="">Tất cả HK</option><option>HK1</option><option>HK2</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Học sinh</th><th>Môn</th><th>HK</th><th>TX</th><th>GK</th><th>CK</th><th>TB</th><th></th></tr></thead><tbody id="grows"></tbody></table></div>`);renderGrades()}
function renderGrades(){let c=document.querySelector('#gc')?.value||'',s=document.querySelector('#gs')?.value||'',m=document.querySelector('#gm')?.value||'';let a=db.grades.filter(g=>(!c||student(g.student_id)?.class_id===c)&&(!s||g.subject===s)&&(!m||g.semester===m));document.querySelector('#grows').innerHTML=a.map(g=>`<tr><td>${esc(student(g.student_id)?.full_name||'')}</td><td>${esc(g.subject)}</td><td>${g.semester}</td><td>${(g.regular||[]).join(', ')}</td><td>${g.mid??''}</td><td>${g.final??''}</td><td><b>${calc(g).toFixed(2)}</b></td><td><button class="linkbtn" onclick="gradeForm('${g.id}')">Sửa</button><button class="linkbtn dangerText" onclick="removeGrade('${g.id}')">Xóa</button></td></tr>`).join('')}
function gradeForm(id=''){let g=db.grades.find(x=>x.id===id)||{regular:[]},rs=(g.regular||[]).join(',');modal(`<h2>${id?'Sửa':'Nhập'} điểm</h2><form onsubmit="saveGrade(event,'${id}')"><div class="formgrid"><label>Học sinh<select name="student" required>${db.students.map(s=>`<option value="${s.id}" ${s.id===g.student_id?'selected':''}>${esc(s.full_name||s.name)} - ${esc(classBy(s.class_id)?.name||'')}</option>`).join('')}</select></label><label>Môn<select name="subject"><option>Toán</option><option>Ngữ văn</option><option>Tin học</option><option>Vật lý</option><option>Hóa học</option><option>Tiếng Anh</option></select></label><label>Học kỳ<select name="semester"><option ${g.semester==='HK1'?'selected':''}>HK1</option><option ${g.semester==='HK2'?'selected':''}>HK2</option></select></label><label>Điểm TX<input name="regular" value="${esc(rs)}" placeholder="8, 9, 8.5"></label><label>Giữa kỳ<input name="mid" type="number" min="0" max="10" step="0.1" value="${g.mid??''}"></label><label>Cuối kỳ<input name="final" type="number" min="0" max="10" step="0.1" value="${g.final??''}"></label></div><p class="hint">Công thức mô phỏng: TX hệ số 1, giữa kỳ hệ số 2, cuối kỳ hệ số 3.</p><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
async function saveGrade(e,id){e.preventDefault();let f=new FormData(e.target),r=(f.get('regular')||'').split(',').map(Number).filter(x=>x>=0&&x<=10),row={student_id:f.get('student'),subject:f.get('subject'),semester:f.get('semester'),regular:r,mid:f.get('mid')===''?null:+f.get('mid'),final:f.get('final')===''?null:+f.get('final')};if(id){Object.assign(db.grades.find(x=>x.id===id),row);if(configured&&session)await push('grades?id=eq.'+id,row,'PATCH')}else{row.id=uid('gr');db.grades.push(row);if(configured&&session)await push('grades',row)}save();closeModal();gradesPage()}
async function removeGrade(id){if(!confirm('Xóa bản ghi điểm?'))return;db.grades=db.grades.filter(x=>x.id!==id);if(configured&&session)await push('grades?id=eq.'+id,{},'DELETE');save();gradesPage()}
function attendancePage(){let date=new Date().toISOString().slice(0,10);shell(header('Điểm danh','Theo dõi chuyên cần theo ngày',`<button class="btn" onclick="saveAttendanceDate()">💾 Lưu điểm danh</button>`)+`<div class="toolbar"><input id="adate" type="date" value="${date}"><select id="aclass"><option value="">Chọn lớp</option>${db.classes.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div id="attendanceBox" class="card empty">Chọn lớp để hiển thị danh sách.</div>`);document.querySelector('#aclass').onchange=renderAttendance}
function renderAttendance(){let c=document.querySelector('#aclass').value,d=document.querySelector('#adate').value,ss=db.students.filter(s=>s.class_id===c);document.querySelector('#attendanceBox').innerHTML=`<table class="table"><thead><tr><th>Học sinh</th><th>Trạng thái</th><th>Ghi chú</th></tr></thead><tbody>${ss.map(s=>{let a=db.attendance.find(x=>x.student_id===s.id&&x.attendance_date===d)||{status:'present',note:''};return `<tr><td><b>${esc(s.full_name||s.name)}</b></td><td><select data-a="${s.id}"><option value="present" ${a.status==='present'?'selected':''}>Có mặt</option><option value="excused" ${a.status==='excused'?'selected':''}>Có phép</option><option value="unexcused" ${a.status==='unexcused'?'selected':''}>Không phép</option></select></td><td><input data-n="${s.id}" value="${esc(a.note||'')}"></td></tr>`}).join('')}</tbody></table>`}
async function saveAttendanceDate(){let c=document.querySelector('#aclass')?.value,d=document.querySelector('#adate')?.value;if(!c){alert('Chọn lớp');return}document.querySelectorAll('[data-a]').forEach(async el=>{let id=el.dataset.a,row={attendance_date:d,class_id:c,student_id:id,status:el.value,note:document.querySelector('[data-n="'+id+'"]')?.value||''},old=db.attendance.find(x=>x.student_id===id&&x.attendance_date===d);if(old){Object.assign(old,row);if(configured&&session)await push('attendance?id=eq.'+old.id,row,'PATCH')}else{row.id=uid('dd');db.attendance.push(row);if(configured&&session)await push('attendance',row)}});save();alert('Đã lưu điểm danh')}
function awardsPage(){shell(header('Khen thưởng','Lịch sử thành tích học sinh',`<button class="btn" onclick="awardForm()">＋ Thêm khen thưởng</button>`)+simpleTable(db.awards,'award'))}
function violationsPage(){shell(header('Vi phạm','Theo dõi rèn luyện và xử lý',`<button class="btn" onclick="violationForm()">＋ Ghi nhận vi phạm</button>`)+simpleTable(db.violations,'violation'))}
function simpleTable(a,type){let award=type==='award';return `<div class="table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Học sinh</th><th>${award?'Loại':'Mức độ'}</th><th>Nội dung</th><th>${award?'':'Xử lý'}</th><th></th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.award_date||x.violation_date)}</td><td>${esc(student(x.student_id)?.full_name||'')}</td><td>${esc(x.type||x.severity)}</td><td>${esc(x.content)}</td><td>${esc(x.handling||'')}</td><td><button class="linkbtn dangerText" onclick="removeRecord('${type}','${x.id}')">Xóa</button></td></tr>`).join('')}</tbody></table></div>`}
function awardForm(){modal(`<h2>Thêm khen thưởng</h2><form onsubmit="saveAward(event)"><div class="formgrid"><label>Học sinh<select name="student">${db.students.map(s=>`<option value="${s.id}">${esc(s.full_name||s.name)}</option>`).join('')}</select></label><label>Ngày<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Loại<select name="type"><option>Học tập</option><option>Phong trào</option><option>Khác</option></select></label><label>Nội dung<textarea name="content" required></textarea></label></div><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
async function saveAward(e){e.preventDefault();let f=new FormData(e.target),row={id:uid('kt'),student_id:f.get('student'),award_date:f.get('date'),type:f.get('type'),content:f.get('content')};db.awards.push(row);if(configured&&session)await push('awards',row);save();closeModal();awardsPage()}
function violationForm(){modal(`<h2>Ghi nhận vi phạm</h2><form onsubmit="saveViolation(event)"><div class="formgrid"><label>Học sinh<select name="student">${db.students.map(s=>`<option value="${s.id}">${esc(s.full_name||s.name)}</option>`).join('')}</select></label><label>Ngày<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Loại<input name="type" value="Nề nếp"></label><label>Mức độ<select name="severity"><option>Nhẹ</option><option>Trung bình</option><option>Nặng</option></select></label><label>Nội dung<textarea name="content" required></textarea></label><label>Hình thức xử lý<input name="handling" placeholder="Nhắc nhở, cam kết..."></label></div><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
async function saveViolation(e){e.preventDefault();let f=new FormData(e.target),row={id:uid('vp'),student_id:f.get('student'),violation_date:f.get('date'),type:f.get('type'),severity:f.get('severity'),content:f.get('content'),handling:f.get('handling')};db.violations.push(row);if(configured&&session)await push('violations',row);save();closeModal();violationsPage()}
async function removeRecord(type,id){if(!confirm('Xóa bản ghi?'))return;let k=type==='award'?'awards':'violations',table=type==='award'?'awards':'violations';db[k]=db[k].filter(x=>x.id!==id);if(configured&&session)await push(table+'?id=eq.'+id,{},'DELETE');save();type==='award'?awardsPage():violationsPage()}
function reportsPage(){let risk=db.students.filter(s=>st(s)!=='Tốt');shell(header('Báo cáo','Thống kê phục vụ giáo viên chủ nhiệm')+`<section class="cards"><div class="card"><div class="label">Tổng học sinh</div><div class="value">${db.students.length}</div></div><div class="card"><div class="label">ĐTB toàn danh sách</div><div class="value">${db.students.length?(db.students.reduce((a,s)=>a+gradeAvg(s.id),0)/db.students.length).toFixed(2):'0.00'}</div></div><div class="card"><div class="label">Khen thưởng</div><div class="value">${db.awards.length}</div></div><div class="card"><div class="label">Vi phạm</div><div class="value">${db.violations.length}</div></div></section><div class="card"><h2>Danh sách cần quan tâm</h2><div class="table-wrap"><table class="table"><thead><tr><th>Học sinh</th><th>Lớp</th><th>ĐTB</th><th>Chuyên cần</th><th>Trạng thái</th></tr></thead><tbody>${risk.map(s=>`<tr><td>${esc(s.full_name||s.name)}</td><td>${esc(classBy(s.class_id)?.name||'')}</td><td>${gradeAvg(s.id).toFixed(2)}</td><td>${rate(s.id)}%</td><td>${st(s)}</td></tr>`).join('')}</tbody></table></div></div><button class="btn" onclick="exportCSV('report')">⬇ Xuất báo cáo CSV</button>`)}
function settingsPage(){shell(header('Cài đặt','Cấu hình hệ thống và đồng bộ dữ liệu')+`<div class="card"><h2>☁️ Kết nối Supabase</h2><p>Trạng thái: <b>${configured?'Đã khai báo cấu hình':'Chưa cấu hình'}</b> • ${session?'Đã đăng nhập':'Chưa đăng nhập'}</p><p>Khóa <b>anon/public</b> có thể dùng ở trình duyệt. Tuyệt đối không đưa service_role key vào GitHub.</p><button class="btn" onclick="syncDown().then(()=>{alert('Đã đồng bộ dữ liệu');render()})">↻ Đồng bộ máy chủ</button><button class="btn secondary" onclick="downloadBackup()">⬇ Sao lưu JSON</button><button class="btn secondary" onclick="resetLocal()">♻ Xóa dữ liệu cục bộ</button></div><div class="card"><h2>📅 Năm học hiện tại</h2><select onchange="changeYear(this.value)">${db.years.map(y=>`<option ${y.name===currentYear?'selected':''}>${esc(y.name)}</option>`).join('')}</select></div>`)}
function modal(html){let x=document.createElement('div');x.className='modal';x.id='modal';x.innerHTML=`<div class="modalbox">${html}</div>`;document.body.appendChild(x)}
function closeModal(){document.querySelector('#modal')?.remove()}
function changeYear(y){currentYear=y;localStorage.setItem('thpt_year',y);render()}
function go(p){page=p;render()}
async function render(){if(!session){renderLogin();return}({dashboard,students:studentsPage,classes:classesPage,grades:gradesPage,attendance:attendancePage,awards:awardsPage,violations:violationsPage,reports:reportsPage,settings:settingsPage}[page]||dashboard)()}
function exportCSV(type){let rows=type==='students'?[['Mã','Họ tên','Lớp','Giới tính','ĐTB','Chuyên cần','Trạng thái'],...db.students.map(s=>[s.code||s.id,s.full_name||s.name,classBy(s.class_id)?.name||'',s.gender,gradeAvg(s.id),rate(s.id),st(s)])]:[['Học sinh','Lớp','ĐTB','Chuyên cần','Trạng thái'],...db.students.map(s=>[s.full_name||s.name,classBy(s.class_id)?.name||'',gradeAvg(s.id),rate(s.id),st(s)])];let csv='\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='bao-cao-hoc-sinh.csv';a.click()}
function downloadBackup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='backup-quan-ly-hoc-sinh.json';a.click()}
function resetLocal(){if(confirm('Xóa dữ liệu cục bộ trên trình duyệt?')){localStorage.removeItem(SKEY);location.reload()}}
Object.assign(window,{go,filterStudents,studentForm,saveStudent,removeStudent,classForm,saveClass,gradeForm,saveGrade,removeGrade,renderGrades,saveAttendanceDate,renderAttendance,awardForm,saveAward,violationForm,saveViolation,removeRecord,closeModal,changeYear,exportCSV,downloadBackup,resetLocal,login,signup,renderSignup,renderLogin,logout,syncDown});
render();
