const KEY='thpt_student_manager_v2';
const seed={
 students:[
  {id:'HS001',name:'Nguyễn Văn An',class:'12A1',gender:'Nam',phone:'0901000001',avg:8.5},
  {id:'HS002',name:'Trần Thị Bình',class:'12A1',gender:'Nữ',phone:'0901000002',avg:9.2},
  {id:'HS003',name:'Lê Văn Cường',class:'12A2',gender:'Nam',phone:'0901000003',avg:6.4},
  {id:'HS004',name:'Phạm Minh Anh',class:'11A1',gender:'Nữ',phone:'0901000004',avg:7.8},
  {id:'HS005',name:'Hoàng Đức Minh',class:'10A1',gender:'Nam',phone:'0901000005',avg:5.8}
 ],
 classes:[['10A1',42],['10A2',41],['11A1',40],['11A2',43],['12A1',42],['12A2',41]],
 subjects:['Toán','Ngữ văn','Tin học','Vật lý','Hóa học','Tiếng Anh'],
 grades:[
  {id:'D001',studentId:'HS001',subject:'Tin học',semester:'HK1',regular:[8.5,9],mid:8.5,final:9},
  {id:'D002',studentId:'HS002',subject:'Tin học',semester:'HK1',regular:[9,9.5],mid:9,final:9.5},
  {id:'D003',studentId:'HS003',subject:'Tin học',semester:'HK1',regular:[6,6.5],mid:6,final:6.5},
  {id:'D004',studentId:'HS004',subject:'Toán',semester:'HK1',regular:[8,7.5],mid:8,final:8},
  {id:'D005',studentId:'HS005',subject:'Toán',semester:'HK1',regular:[5,6],mid:5.5,final:5.5}
 ],
 attendance:[
  {id:'DD001',date:'2026-09-03',class:'12A1',studentId:'HS001',status:'present',note:''},
  {id:'DD002',date:'2026-09-03',class:'12A1',studentId:'HS002',status:'present',note:''},
  {id:'DD003',date:'2026-09-03',class:'12A2',studentId:'HS003',status:'unexcused',note:'Nghỉ không phép'},
  {id:'DD004',date:'2026-09-03',class:'11A1',studentId:'HS004',status:'excused',note:'Có lý do'},
  {id:'DD005',date:'2026-09-03',class:'10A1',studentId:'HS005',status:'present',note:''}
 ],
 awards:[{id:'KT001',studentId:'HS002',date:'2026-08-30',type:'Học tập',content:'Đạt thành tích cao trong học tập'}],
 violations:[{id:'VP001',studentId:'HS003',date:'2026-09-02',type:'Nề nếp',severity:'Nhẹ',content:'Đi học muộn',handling:'Nhắc nhở'}]
};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
const app=document.querySelector('#app');let page='dashboard';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,5);
const student=id=>db.students.find(s=>s.id===id);
function calcGrade(g){const r=(g.regular||[]).map(Number).filter(Number.isFinite);const w=r.length+2+3;return w?((r.reduce((a,b)=>a+b,0)+Number(g.mid||0)*2+Number(g.final||0)*3)/w):0}
function attendanceRate(id){const a=db.attendance.filter(x=>x.studentId===id);return a.length?Math.round(a.filter(x=>x.status==='present').length/a.length*100):100}
function status(avg,rate){if(avg<5||rate<85)return 'Cần hỗ trợ';if(avg<6.5||rate<90)return 'Cần chú ý';if(avg<8)return 'Khá';return 'Tốt'}
function syncAverages(){db.students.forEach(s=>{const gs=db.grades.filter(g=>g.studentId===s.id);s.avg=gs.length?Number((gs.reduce((a,g)=>a+calcGrade(g),0)/gs.length).toFixed(2)):s.avg||0});save()}
syncAverages();
function shell(content){app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand">🎓 QUẢN LÝ HỌC SINH<span>THPT • Năm học 2026–2027</span></div><nav class="nav">${[['dashboard','🏠 Tổng quan'],['students','👨‍🎓 Học sinh'],['classes','🏫 Lớp học'],['grades','📊 Điểm số'],['attendance','📅 Điểm danh'],['awards','🏆 Khen thưởng'],['violations','⚠️ Vi phạm'],['reports','📄 Báo cáo']].map(x=>`<button class="${page===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}</nav></aside><main class="main">${content}</main></div>`}
function header(title,sub='Năm học 2026–2027',action=''){return `<div class="top"><div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function dashboard(){syncAverages();const total=db.students.length,male=db.students.filter(s=>s.gender==='Nam').length,female=total-male,attention=db.students.filter(s=>status(s.avg,attendanceRate(s.id))!=='Tốt').length,unexc=db.attendance.filter(a=>a.status==='unexcused').length;const good=db.students.filter(s=>s.avg>=8).length,medium=db.students.filter(s=>s.avg>=6.5&&s.avg<8).length,pass=db.students.filter(s=>s.avg>=5&&s.avg<6.5).length; shell(header('Tổng quan','Xin chào giáo viên 👋 • Dữ liệu được lưu trên trình duyệt')+`<section class="cards"><div class="card"><div class="label">👨‍🎓 Học sinh</div><div class="value">${total}</div></div><div class="card"><div class="label">🏫 Lớp học</div><div class="value">${db.classes.length}</div></div><div class="card"><div class="label">👨 Nam</div><div class="value">${male}</div></div><div class="card"><div class="label">👩 Nữ</div><div class="value">${female}</div></div></section><section class="grid"><div class="card"><h2>📊 Kết quả học tập</h2><div>Đạt từ 8,0 <b>${good}</b><div class="bar"><i style="width:${total?good/total*100:0}%"></i></div></div><div>6,5–7,9 <b>${medium}</b><div class="bar"><i style="width:${total?medium/total*100:0}%"></i></div></div><div>5,0–6,4 <b>${pass}</b><div class="bar"><i style="width:${total?pass/total*100:0}%"></i></div></div><div>Dưới 5,0 <b>${total-good-medium-pass}</b><div class="bar"><i style="width:${total?(total-good-medium-pass)/total*100:0}%"></i></div></div></div><div class="card"><h2>🔔 Cần quan tâm</h2><div class="alert">⚠️ ${attention} học sinh cần theo dõi học tập/chuyên cần</div><div class="alert">⚠️ ${unexc} lượt nghỉ không phép đã ghi nhận</div><div class="alert">🏆 ${db.awards.length} lượt khen thưởng</div></div></section>`)}
function studentsPage(){shell(header('Quản lý học sinh','Danh sách học sinh toàn trường',`<button class="btn" onclick="studentForm()">＋ Thêm học sinh</button>`)+`<div class="toolbar"><input id="q" placeholder="🔍 Tìm theo mã hoặc họ tên..." oninput="filterStudents()"><select id="classFilter" onchange="filterStudents()"><option value="">Tất cả lớp</option>${db.classes.map(c=>`<option>${c[0]}</option>`).join('')}</select><button class="btn secondary" onclick="exportCSV('students')">⬇ Xuất CSV</button></div><div class="table-wrap"><table class="table"><thead><tr><th>STT</th><th>Mã HS</th><th>Họ và tên</th><th>Lớp</th><th>Giới tính</th><th>ĐTB</th><th>Chuyên cần</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody id="studentRows">${studentRows(db.students)}</tbody></table></div>`)}
function studentRows(list){return list.map((s,i)=>{const rate=attendanceRate(s.id),st=status(s.avg,rate);return `<tr><td>${i+1}</td><td>${esc(s.id)}</td><td><b>${esc(s.name)}</b></td><td>${esc(s.class)}</td><td>${esc(s.gender)}</td><td>${Number(s.avg).toFixed(2)}</td><td>${rate}%</td><td><span class="badge ${st==='Tốt'?'ok':st==='Khá'?'info':st==='Cần chú ý'?'warn':'danger'}">${st}</span></td><td><button class="linkbtn" onclick="studentForm('${s.id}')">Sửa</button><button class="linkbtn dangerText" onclick="deleteStudent('${s.id}')">Xóa</button></td></tr>`}).join('')}
function filterStudents(){const q=(document.querySelector('#q')?.value||'').toLowerCase(),c=document.querySelector('#classFilter')?.value||'';const rows=db.students.filter(s=>(s.name.toLowerCase().includes(q)||s.id.toLowerCase().includes(q))&&(!c||s.class===c));document.querySelector('#studentRows').innerHTML=studentRows(rows)}
function studentForm(id=''){const s=student(id)||{id:'',name:'',class:db.classes[0]?.[0]||'',gender:'Nam',phone:''};modal(`<h2>${id?'Sửa':'Thêm'} học sinh</h2><form onsubmit="saveStudent(event,'${id}')"><div class="formgrid"><label>Mã HS<input name="sid" required value="${esc(s.id)}" ${id?'readonly':''}></label><label>Họ và tên<input name="name" required value="${esc(s.name)}"></label><label>Lớp<select name="class">${db.classes.map(c=>`<option ${c[0]===s.class?'selected':''}>${c[0]}</option>`).join('')}</select></label><label>Giới tính<select name="gender"><option ${s.gender==='Nam'?'selected':''}>Nam</option><option ${s.gender==='Nữ'?'selected':''}>Nữ</option></select></label><label>Số điện thoại<input name="phone" value="${esc(s.phone||'')}"></label></div><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
function saveStudent(e,id){e.preventDefault();const f=new FormData(e.target);if(id){Object.assign(student(id),{name:f.get('name'),class:f.get('class'),gender:f.get('gender'),phone:f.get('phone')})}else{if(student(f.get('sid'))){alert('Mã học sinh đã tồn tại');return}db.students.push({id:f.get('sid'),name:f.get('name'),class:f.get('class'),gender:f.get('gender'),phone:f.get('phone'),avg:0})}save();closeModal();studentsPage()}
function deleteStudent(id){if(!confirm('Xóa học sinh này và các dữ liệu liên quan?'))return;db.students=db.students.filter(s=>s.id!==id);db.grades=db.grades.filter(g=>g.studentId!==id);db.attendance=db.attendance.filter(a=>a.studentId!==id);db.awards=db.awards.filter(a=>a.studentId!==id);db.violations=db.violations.filter(v=>v.studentId!==id);save();studentsPage()}
function classesPage(){shell(header('Quản lý lớp học','Danh sách lớp theo năm học')+`<div class="table-wrap"><table class="table"><thead><tr><th>Lớp</th><th>Sĩ số</th><th>Nam</th><th>Nữ</th><th>Chuyên cần</th><th>ĐTB</th></tr></thead><tbody>${db.classes.map(c=>{const ss=db.students.filter(s=>s.class===c[0]);const avg=ss.length?(ss.reduce((a,s)=>a+s.avg,0)/ss.length).toFixed(2):'—';const male=ss.filter(s=>s.gender==='Nam').length;const rate=ss.length?Math.round(ss.reduce((a,s)=>a+attendanceRate(s.id),0)/ss.length):0;return `<tr><td><b>${c[0]}</b></td><td>${c[1]}</td><td>${male}</td><td>${ss.length-male}</td><td>${rate||96.8}%</td><td>${avg}</td></tr>`}).join('')}</tbody></table></div>`)}
function gradesPage(){shell(header('Quản lý điểm số','Nhập và theo dõi điểm theo môn/học kỳ',`<button class="btn" onclick="gradeForm()">＋ Nhập điểm</button>`)+`<div class="toolbar"><select id="gradeClass" onchange="renderGrades()"><option value="">Tất cả lớp</option>${db.classes.map(c=>`<option>${c[0]}</option>`).join('')}</select><select id="gradeSubject" onchange="renderGrades()"><option value="">Tất cả môn</option>${db.subjects.map(x=>`<option>${x}</option>`).join('')}</select><select id="gradeSem" onchange="renderGrades()"><option value="">Tất cả học kỳ</option><option>HK1</option><option>HK2</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Học sinh</th><th>Lớp</th><th>Môn</th><th>HK</th><th>Điểm TX</th><th>Giữa kỳ</th><th>Cuối kỳ</th><th>TB</th><th></th></tr></thead><tbody id="gradeRows"></tbody></table></div>`);renderGrades()}
function renderGrades(){const c=document.querySelector('#gradeClass')?.value||'',sub=document.querySelector('#gradeSubject')?.value||'',sem=document.querySelector('#gradeSem')?.value||'';const list=db.grades.filter(g=>(!c||student(g.studentId)?.class===c)&&(!sub||g.subject===sub)&&(!sem||g.semester===sem));document.querySelector('#gradeRows').innerHTML=list.map(g=>`<tr><td><b>${esc(student(g.studentId)?.name||g.studentId)}</b></td><td>${esc(student(g.studentId)?.class||'')}</td><td>${esc(g.subject)}</td><td>${g.semester}</td><td>${(g.regular||[]).join(', ')}</td><td>${g.mid}</td><td>${g.final}</td><td><b>${calcGrade(g).toFixed(2)}</b></td><td><button class="linkbtn" onclick="gradeForm('${g.id}')">Sửa</button><button class="linkbtn dangerText" onclick="deleteGrade('${g.id}')">Xóa</button></td></tr>`).join('')||`<tr><td colspan="9" class="emptyCell">Chưa có dữ liệu phù hợp.</td></tr>`}
function gradeForm(id=''){const g=db.grades.find(x=>x.id===id)||{studentId:db.students[0]?.id||'',subject:db.subjects[0],semester:'HK1',regular:['',''],mid:'',final:''};modal(`<h2>${id?'Sửa':'Nhập'} điểm</h2><form onsubmit="saveGrade(event,'${id}')"><div class="formgrid"><label>Học sinh<select name="student">${db.students.map(s=>`<option value="${s.id}" ${s.id===g.studentId?'selected':''}>${esc(s.name)} - ${s.class}</option>`).join('')}</select></label><label>Môn<select name="subject">${db.subjects.map(x=>`<option ${x===g.subject?'selected':''}>${x}</option>`).join('')}</select></label><label>Học kỳ<select name="semester"><option ${g.semester==='HK1'?'selected':''}>HK1</option><option ${g.semester==='HK2'?'selected':''}>HK2</option></select></label><label>Điểm TX 1<input type="number" step="0.1" min="0" max="10" name="r1" value="${g.regular?.[0]??''}"></label><label>Điểm TX 2<input type="number" step="0.1" min="0" max="10" name="r2" value="${g.regular?.[1]??''}"></label><label>Giữa kỳ<input type="number" step="0.1" min="0" max="10" name="mid" value="${g.mid??''}" required></label><label>Cuối kỳ<input type="number" step="0.1" min="0" max="10" name="final" value="${g.final??''}" required></label></div><p class="hint">TB mô phỏng: các điểm TX hệ số 1, giữa kỳ hệ số 2, cuối kỳ hệ số 3.</p><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
function saveGrade(e,id){e.preventDefault();const f=new FormData(e.target);const regular=[f.get('r1'),f.get('r2')].filter(x=>x!=='').map(Number);const data={studentId:f.get('student'),subject:f.get('subject'),semester:f.get('semester'),regular,mid:Number(f.get('mid')),final:Number(f.get('final'))};if(id)Object.assign(db.grades.find(x=>x.id===id),data);else db.grades.push({id:uid('D'),...data});save();syncAverages();closeModal();gradesPage()}
function deleteGrade(id){if(confirm('Xóa bản ghi điểm?')){db.grades=db.grades.filter(g=>g.id!==id);save();syncAverages();gradesPage()}}
function attendancePage(){const today=new Date().toISOString().slice(0,10);shell(header('Điểm danh','Theo dõi chuyên cần theo ngày và lớp',`<button class="btn" onclick="attendanceForm()">＋ Ghi điểm danh</button>`)+`<div class="toolbar"><input id="attDate" type="date" value="${today}" onchange="renderAttendance()"><select id="attClass" onchange="renderAttendance()"><option value="">Tất cả lớp</option>${db.classes.map(c=>`<option>${c[0]}</option>`).join('')}</select><button class="btn secondary" onclick="exportCSV('attendance')">⬇ Xuất CSV</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Học sinh</th><th>Lớp</th><th>Trạng thái</th><th>Ghi chú</th><th></th></tr></thead><tbody id="attRows"></tbody></table></div>`);renderAttendance()}
function attLabel(s){return s==='present'?'Có mặt':s==='excused'?'Có phép':'Không phép'}
function renderAttendance(){const d=document.querySelector('#attDate')?.value,c=document.querySelector('#attClass')?.value||'';const list=db.attendance.filter(a=>(!d||a.date===d)&&(!c||a.class===c));document.querySelector('#attRows').innerHTML=list.map(a=>`<tr><td>${a.date}</td><td><b>${esc(student(a.studentId)?.name||a.studentId)}</b></td><td>${a.class}</td><td><span class="badge ${a.status==='present'?'ok':a.status==='excused'?'info':'danger'}">${attLabel(a.status)}</span></td><td>${esc(a.note)}</td><td><button class="linkbtn" onclick="attendanceForm('${a.id}')">Sửa</button><button class="linkbtn dangerText" onclick="deleteAttendance('${a.id}')">Xóa</button></td></tr>`).join('')||`<tr><td colspan="6" class="emptyCell">Không có dữ liệu điểm danh.</td></tr>`}
function attendanceForm(id=''){const a=db.attendance.find(x=>x.id===id)||{date:new Date().toISOString().slice(0,10),studentId:db.students[0]?.id||'',status:'present',note:''};const cls=student(a.studentId)?.class||'';modal(`<h2>${id?'Sửa':'Ghi'} điểm danh</h2><form onsubmit="saveAttendance(event,'${id}')"><div class="formgrid"><label>Ngày<input type="date" name="date" required value="${a.date}"></label><label>Học sinh<select name="student">${db.students.map(s=>`<option value="${s.id}" ${s.id===a.studentId?'selected':''}>${esc(s.name)} - ${s.class}</option>`).join('')}</select></label><label>Trạng thái<select name="status"><option value="present" ${a.status==='present'?'selected':''}>Có mặt</option><option value="excused" ${a.status==='excused'?'selected':''}>Có phép</option><option value="unexcused" ${a.status==='unexcused'?'selected':''}>Không phép</option></select></label><label>Ghi chú<input name="note" value="${esc(a.note||'')}" placeholder="Lý do, ghi chú..."></label></div><p class="hint">Lớp của học sinh: <b>${cls||'—'}</b></p><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
function saveAttendance(e,id){e.preventDefault();const f=new FormData(e.target),sid=f.get('student'),data={date:f.get('date'),studentId:sid,class:student(sid)?.class||'',status:f.get('status'),note:f.get('note')};if(id)Object.assign(db.attendance.find(x=>x.id===id),data);else db.attendance.push({id:uid('DD'),...data});save();closeModal();attendancePage()}
function deleteAttendance(id){if(confirm('Xóa bản ghi điểm danh?')){db.attendance=db.attendance.filter(x=>x.id!==id);save();attendancePage()}}
function awardsPage(){shell(header('Khen thưởng','Lịch sử thành tích và tuyên dương',`<button class="btn" onclick="awardForm()">＋ Thêm khen thưởng</button>`)+`<div class="table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Học sinh</th><th>Lớp</th><th>Loại</th><th>Nội dung</th><th></th></tr></thead><tbody>${db.awards.map(a=>`<tr><td>${a.date}</td><td><b>${esc(student(a.studentId)?.name||a.studentId)}</b></td><td>${student(a.studentId)?.class||''}</td><td>${esc(a.type)}</td><td>${esc(a.content)}</td><td><button class="linkbtn" onclick="awardForm('${a.id}')">Sửa</button><button class="linkbtn dangerText" onclick="deleteAward('${a.id}')">Xóa</button></td></tr>`).join('')||`<tr><td colspan="6" class="emptyCell">Chưa có khen thưởng.</td></tr>`}</tbody></table></div>`)}
function awardForm(id=''){const a=db.awards.find(x=>x.id===id)||{date:new Date().toISOString().slice(0,10),studentId:db.students[0]?.id||'',type:'Học tập',content:''};modal(`<h2>${id?'Sửa':'Thêm'} khen thưởng</h2><form onsubmit="saveAward(event,'${id}')"><div class="formgrid"><label>Ngày<input type="date" name="date" value="${a.date}" required></label><label>Học sinh<select name="student">${db.students.map(s=>`<option value="${s.id}" ${s.id===a.studentId?'selected':''}>${esc(s.name)} - ${s.class}</option>`).join('')}</select></label><label>Loại<select name="type"><option ${a.type==='Học tập'?'selected':''}>Học tập</option><option ${a.type==='Phong trào'?'selected':''}>Phong trào</option><option ${a.type==='Khác'?'selected':''}>Khác</option></select></label><label>Nội dung<input name="content" required value="${esc(a.content)}"></label></div><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
function saveAward(e,id){e.preventDefault();const f=new FormData(e.target),data={date:f.get('date'),studentId:f.get('student'),type:f.get('type'),content:f.get('content')};if(id)Object.assign(db.awards.find(x=>x.id===id),data);else db.awards.push({id:uid('KT'),...data});save();closeModal();awardsPage()}
function deleteAward(id){if(confirm('Xóa khen thưởng?')){db.awards=db.awards.filter(x=>x.id!==id);save();awardsPage()}}
function violationsPage(){shell(header('Vi phạm','Theo dõi nề nếp, mức độ và xử lý',`<button class="btn" onclick="violationForm()">＋ Ghi vi phạm</button>`)+`<div class="table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Học sinh</th><th>Lớp</th><th>Loại</th><th>Mức độ</th><th>Nội dung</th><th>Xử lý</th><th></th></tr></thead><tbody>${db.violations.map(v=>`<tr><td>${v.date}</td><td><b>${esc(student(v.studentId)?.name||v.studentId)}</b></td><td>${student(v.studentId)?.class||''}</td><td>${esc(v.type)}</td><td><span class="badge ${v.severity==='Nặng'?'danger':v.severity==='Trung bình'?'warn':'info'}">${v.severity}</span></td><td>${esc(v.content)}</td><td>${esc(v.handling)}</td><td><button class="linkbtn" onclick="violationForm('${v.id}')">Sửa</button><button class="linkbtn dangerText" onclick="deleteViolation('${v.id}')">Xóa</button></td></tr>`).join('')||`<tr><td colspan="8" class="emptyCell">Chưa có vi phạm.</td></tr>`}</tbody></table></div>`)}
function violationForm(id=''){const v=db.violations.find(x=>x.id===id)||{date:new Date().toISOString().slice(0,10),studentId:db.students[0]?.id||'',type:'Nề nếp',severity:'Nhẹ',content:'',handling:'Nhắc nhở'};modal(`<h2>${id?'Sửa':'Ghi'} vi phạm</h2><form onsubmit="saveViolation(event,'${id}')"><div class="formgrid"><label>Ngày<input type="date" name="date" value="${v.date}" required></label><label>Học sinh<select name="student">${db.students.map(s=>`<option value="${s.id}" ${s.id===v.studentId?'selected':''}>${esc(s.name)} - ${s.class}</option>`).join('')}</select></label><label>Loại<select name="type"><option>Nề nếp</option><option>Học tập</option><option>Khác</option></select></label><label>Mức độ<select name="severity"><option ${v.severity==='Nhẹ'?'selected':''}>Nhẹ</option><option ${v.severity==='Trung bình'?'selected':''}>Trung bình</option><option ${v.severity==='Nặng'?'selected':''}>Nặng</option></select></label><label>Nội dung<input name="content" required value="${esc(v.content)}"></label><label>Xử lý<input name="handling" value="${esc(v.handling)}"></label></div><div class="modalActions"><button type="button" class="btn secondary" onclick="closeModal()">Hủy</button><button class="btn">Lưu</button></div></form>`)}
function saveViolation(e,id){e.preventDefault();const f=new FormData(e.target),data={date:f.get('date'),studentId:f.get('student'),type:f.get('type'),severity:f.get('severity'),content:f.get('content'),handling:f.get('handling')};if(id)Object.assign(db.violations.find(x=>x.id===id),data);else db.violations.push({id:uid('VP'),...data});save();closeModal();violationsPage()}
function deleteViolation(id){if(confirm('Xóa vi phạm?')){db.violations=db.violations.filter(x=>x.id!==id);save();violationsPage()}}
function reportsPage(){syncAverages();const total=db.students.length,avg=total?(db.students.reduce((a,s)=>a+s.avg,0)/total).toFixed(2):'0.00',att=total?Math.round(db.students.reduce((a,s)=>a+attendanceRate(s.id),0)/total):0,low=db.students.filter(s=>s.avg<5),risk=db.students.filter(s=>status(s.avg,attendanceRate(s.id))==='Cần hỗ trợ');shell(header('Báo cáo & thống kê','Tổng hợp nhanh phục vụ giáo viên')+`<section class="cards"><div class="card"><div class="label">ĐTB toàn bộ HS</div><div class="value">${avg}</div></div><div class="card"><div class="label">Chuyên cần TB</div><div class="value">${att}%</div></div><div class="card"><div class="label">Khen thưởng</div><div class="value">${db.awards.length}</div></div><div class="card"><div class="label">Vi phạm</div><div class="value">${db.violations.length}</div></div></section><section class="reportGrid"><div class="card"><h2>📚 Thống kê theo lớp</h2><table class="mini"><thead><tr><th>Lớp</th><th>Sĩ số</th><th>ĐTB</th><th>CC</th></tr></thead><tbody>${db.classes.map(c=>{const ss=db.students.filter(s=>s.class===c[0]),a=ss.length?(ss.reduce((x,s)=>x+s.avg,0)/ss.length).toFixed(2):'—',r=ss.length?Math.round(ss.reduce((x,s)=>x+attendanceRate(s.id),0)/ss.length):0;return `<tr><td>${c[0]}</td><td>${c[1]}</td><td>${a}</td><td>${r||'—'}%</td></tr>`}).join('')}</tbody></table></div><div class="card"><h2>🔔 Danh sách cần hỗ trợ</h2>${risk.length?risk.map(s=>`<div class="risk"><b>${esc(s.name)}</b> — ${s.class}<span>ĐTB ${s.avg.toFixed(2)} • CC ${attendanceRate(s.id)}%</span></div>`).join(''):'<p>Không có học sinh thuộc nhóm cần hỗ trợ.</p>'}</div></section><section class="card"><h2>📉 Học sinh có ĐTB dưới 5,0</h2>${low.length?`<table class="mini"><thead><tr><th>Họ tên</th><th>Lớp</th><th>ĐTB</th></tr></thead><tbody>${low.map(s=>`<tr><td>${esc(s.name)}</td><td>${s.class}</td><td>${s.avg.toFixed(2)}</td></tr>`).join('')}</tbody></table>`:'<p>Không có học sinh dưới 5,0 trong dữ liệu hiện tại.</p>'}</section><button class="btn" onclick="exportCSV('report')">⬇ Xuất báo cáo CSV</button>`)}
function modal(html){document.getElementById('modal')?.remove();const d=document.createElement('div');d.id='modal';d.className='modal';d.innerHTML=`<div class="modalBox">${html}</div>`;document.body.appendChild(d)}
function closeModal(){document.getElementById('modal')?.remove()}
function exportCSV(type){let rows=[];if(type==='students'){rows=[['Mã HS','Họ tên','Lớp','Giới tính','ĐTB','Chuyên cần'],...db.students.map(s=>[s.id,s.name,s.class,s.gender,s.avg,attendanceRate(s.id)])]}else if(type==='attendance'){rows=[['Ngày','Mã HS','Họ tên','Lớp','Trạng thái','Ghi chú'],...db.attendance.map(a=>[a.date,a.studentId,student(a.studentId)?.name||'',a.class,attLabel(a.status),a.note])]}else{rows=[['Lớp','Sĩ số','ĐTB','Chuyên cần'],...db.classes.map(c=>{const ss=db.students.filter(s=>s.class===c[0]);return [c[0],c[1],ss.length?(ss.reduce((a,s)=>a+s.avg,0)/ss.length).toFixed(2):'',ss.length?Math.round(ss.reduce((a,s)=>a+attendanceRate(s.id),0)/ss.length):'']})]}const csv='\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bao-cao-hoc-sinh-${type}.csv`;a.click();URL.revokeObjectURL(url)}
function resetDemo(){if(confirm('Khôi phục dữ liệu mẫu? Dữ liệu hiện tại sẽ bị thay thế.')){localStorage.removeItem(KEY);location.reload()}}
function go(p){page=p;({dashboard,students:studentsPage,classes:classesPage,grades:gradesPage,attendance:attendancePage,awards:awardsPage,violations:violationsPage,reports:reportsPage}[p]||dashboard)()}
Object.assign(window,{go,filterStudents,studentForm,saveStudent,deleteStudent,gradeForm,renderGrades,saveGrade,deleteGrade,attendanceForm,renderAttendance,saveAttendance,deleteAttendance,awardForm,saveAward,deleteAward,violationForm,saveViolation,deleteViolation,closeModal,exportCSV,resetDemo});
dashboard();