const students=[{id:'HS001',name:'Nguyễn Văn An',class:'12A1',gender:'Nam',avg:8.5,attendance:98,status:'Tốt'},{id:'HS002',name:'Trần Thị Bình',class:'12A1',gender:'Nữ',avg:9.2,attendance:100,status:'Tốt'},{id:'HS003',name:'Lê Văn Cường',class:'12A2',gender:'Nam',avg:6.4,attendance:91,status:'Cần chú ý'},{id:'HS004',name:'Phạm Minh Anh',class:'11A1',gender:'Nữ',avg:7.8,attendance:96,status:'Khá'},{id:'HS005',name:'Hoàng Đức Minh',class:'10A1',gender:'Nam',avg:5.8,attendance:88,status:'Cần hỗ trợ'}];
const classes=[['10A1',42],['10A2',41],['11A1',40],['11A2',43],['12A1',42],['12A2',41]];
const app=document.querySelector('#app');let page='dashboard';
function shell(content){app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand">🎓 QUẢN LÝ HỌC SINH<span>THPT • Năm học 2026–2027</span></div><nav class="nav">${[['dashboard','🏠 Tổng quan'],['students','👨‍🎓 Học sinh'],['classes','🏫 Lớp học'],['grades','📊 Điểm số'],['attendance','📅 Điểm danh'],['awards','🏆 Khen thưởng'],['violations','⚠️ Vi phạm'],['reports','📄 Báo cáo']].map(x=>`<button class="${page===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}</nav></aside><main class="main">${content}</main></div>`}
function header(title,sub='Năm học 2026–2027'){return `<div class="top"><div><h1>${title}</h1><p>${sub}</p></div><button class="btn">＋ Thêm mới</button></div>`}
function dashboard(){shell(header('Tổng quan','Xin chào giáo viên 👋 • Năm học 2026–2027')+`<section class="cards"><div class="card"><div class="label">👨‍🎓 Học sinh</div><div class="value">1.245</div></div><div class="card"><div class="label">🏫 Lớp học</div><div class="value">36</div></div><div class="card"><div class="label">👨 Nam</div><div class="value">620</div></div><div class="card"><div class="label">👩 Nữ</div><div class="value">625</div></div></section><section class="grid"><div class="card"><h2>📊 Kết quả học tập</h2><div>Giỏi <b>32%</b><div class="bar"><i style="width:32%"></i></div></div><div>Khá <b>41%</b><div class="bar"><i style="width:41%"></i></div></div><div>Đạt <b>21%</b><div class="bar"><i style="width:21%"></i></div></div><div>Chưa đạt <b>6%</b><div class="bar"><i style="width:6%"></i></div></div></div><div class="card"><h2>🔔 Cần quan tâm</h2><div class="alert">⚠️ 11 học sinh nghỉ học nhiều</div><div class="alert">⚠️ 7 học sinh có điểm giảm</div><div class="alert">⚠️ 3 học sinh cần theo dõi rèn luyện</div></div></section>`)}
function studentsPage(){shell(header('Quản lý học sinh','Danh sách học sinh toàn trường')+`<div class="toolbar"><input id="q" placeholder="🔍 Tìm theo mã hoặc họ tên..." oninput="filterStudents()"><select id="classFilter" onchange="filterStudents()"><option value="">Tất cả lớp</option>${classes.map(c=>`<option>${c[0]}</option>`).join('')}</select><button class="btn secondary">⬇ Xuất Excel</button></div><div class="table-wrap"><table class="table"><thead><tr><th>STT</th><th>Mã HS</th><th>Họ và tên</th><th>Lớp</th><th>Giới tính</th><th>ĐTB</th><th>Chuyên cần</th><th>Trạng thái</th></tr></thead><tbody id="studentRows">${studentRows(students)}</tbody></table></div>`)}
function studentRows(list){return list.map((s,i)=>`<tr><td>${i+1}</td><td>${s.id}</td><td><b>${s.name}</b></td><td>${s.class}</td><td>${s.gender}</td><td>${s.avg}</td><td>${s.attendance}%</td><td><span class="badge">${s.status}</span></td></tr>`).join('')}
function filterStudents(){const q=document.querySelector('#q').value.toLowerCase(),c=document.querySelector('#classFilter').value;document.querySelector('#studentRows').innerHTML=studentRows(students.filter(s=>(s.name.toLowerCase().includes(q)||s.id.toLowerCase().includes(q))&&(!c||s.class===c)))}
function classesPage(){shell(header('Quản lý lớp học','Danh sách lớp theo năm học')+`<div class="table-wrap"><table class="table"><thead><tr><th>Lớp</th><th>Sĩ số</th><th>Nam</th><th>Nữ</th><th>Chuyên cần</th></tr></thead><tbody>${classes.map(c=>`<tr><td><b>${c[0]}</b></td><td>${c[1]}</td><td>${Math.floor(c[1]*.48)}</td><td>${Math.ceil(c[1]*.52)}</td><td>96.8%</td></tr>`).join('')}</tbody></table></div>`)}
function generic(title,desc){shell(header(title,desc)+`<div class="card empty">🚧 Module <b>${title}</b> đang được xây dựng trong Giai đoạn 2–3.<br><br>Cấu trúc hệ thống đã sẵn sàng để kết nối cơ sở dữ liệu.</div>`)}
function go(p){page=p;if(p==='dashboard')dashboard();else if(p==='students')studentsPage();else if(p==='classes')classesPage();else generic({grades:'Điểm số',attendance:'Điểm danh',awards:'Khen thưởng',violations:'Vi phạm',reports:'Báo cáo'}[p],'Quản lý dữ liệu');}window.go=go;window.filterStudents=filterStudents;dashboard();
